### ISSUE TITLE
params.php is not suitable for expectation, is this a bug?

### ISSUE THREAD

**Issue by kids-return** [hiqdev/composer-config-plugin#27]
.env 
```
AUTH_DEFAULT_ROLES=guest,test,test2
```
params.php
```php
return [
    'auth.defaultRoles' => explode(',', env('AUTH_DEFAULT_ROLES', 'guest')),
    'auth.default.roles' => explode(',', env('AUTH_DEFAULT_ROLES', 'guest')),
];
```

result
```php
return [
  'auth.defaultRoles' => 
  array (
    0 => 'guest',
    1 => 'test',
    2 => 'test2',
  ),
  'auth.default.roles' => 'guest,test,test2',
]
```

expected result
```php
return [
  'auth.defaultRoles' => 
  array (
    0 => 'guest',
    1 => 'test',
    2 => 'test2',
  ),
  'auth.default.roles' => 
  array (
    0 => 'guest',
    1 => 'test',
    2 => 'test2',
  ),
]
```

**Comment by kids-return** [comment]
The problem may be here
https://github.com/hiqdev/composer-config-plugin/blob/597227a727f51aeb36f70837039a8358714a1aa5/src/configs/Params.php#L30

**Comment by hiqsol** [comment]
It is intentional behavior.
The idea is simplifying passing values from `.env` to config.
.env values are copied to params with corresponding name without writing code for it.
It allows to have default values and easily change them with .env

I prefer to organize files like this:

.env:

    AUTH_DEFAULT_ROLES=guest,test,test2

config/params.php:

```php
return [
    'auth.default.roles' => 'guest', /// It's the default value
];
```
    
config/common.php:

```php
return [
    'some-service' => [
        'class' => \my\Class::class,
        'roles' => explode(',', $params['auth.default.roles']),
    ],
];
```

The exploding is moved  from params to the config file.
